language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
after_success:
  - npm run test
  - npm run check-coverage
  - npm run report-coverage
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
